# Generated by Django 4.1 on 2024-11-18 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_image', models.ImageField(upload_to='outputs/')),
                ('detection_details', models.TextField()),
                ('uploaded_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mask_detector.uploadedimage')),
            ],
        ),
    ]
